CREATE TABLE refresh_tokens(
    id  BIGSERIAL PRIMARY KEY,
    token  VARCHAR(255) NOT NULL UNIQUE ,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at TIMESTAMP NOT NULL,
    creates_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);